# Generated by Django 2.0.4 on 2018-04-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('shift', models.FileField(upload_to='shifts')),
            ],
        ),
        migrations.CreateModel(
            name='Timecards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecard', models.FileField(upload_to='timecards')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=95)),
                ('worker_type', models.CharField(max_length=95)),
            ],
        ),
        migrations.AddField(
            model_name='timecards',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djsg.Workers'),
        ),
    ]
