# Generated by Django 2.0.4 on 2018-04-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shifts',
        ),
        migrations.RemoveField(
            model_name='timecards',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='worker_type',
        ),
        migrations.AddField(
            model_name='workers',
            name='mail',
            field=models.CharField(default='none', max_length=95),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='w_num',
            field=models.CharField(default='none', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='worker_fname',
            field=models.CharField(default='none', max_length=95),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Timecards',
        ),
    ]
